//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FiftyOne.Pipeline.CloudRequestEngine {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FiftyOne.Pipeline.CloudRequestEngine.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to determine the complex type associated with this property. No c# property found matching definition {0}.{1}..
        /// </summary>
        internal static string ExceptionCloudComplexPropertyType {
            get {
                return ResourceManager.GetString("ExceptionCloudComplexPropertyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error returned from 51Degrees cloud service: {0}.
        /// </summary>
        internal static string ExceptionCloudError {
            get {
                return ResourceManager.GetString("ExceptionCloudError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple errors returned from 51Degrees cloud service. See inner exceptions for details..
        /// </summary>
        internal static string ExceptionCloudErrorsMultiple {
            get {
                return ResourceManager.GetString("ExceptionCloudErrorsMultiple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to determine the type associated with this property. No c# property found matching definition {0}.{1} and json type &apos;{2}&apos; is not mapped.   .
        /// </summary>
        internal static string ExceptionCloudPropertyType {
            get {
                return ResourceManager.GetString("ExceptionCloudPropertyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error waiting for response from the cloud service..
        /// </summary>
        internal static string ExceptionCloudResponseFailure {
            get {
                return ResourceManager.GetString("ExceptionCloudResponseFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load aspect properties for element &apos;{0}&apos;. This is because your resource key does not include access to any properties under &apos;{0}&apos;. For more details on resource keys, see our explainer: https://51degrees.com/documentation/_info__resource_keys.html.
        /// </summary>
        internal static string ExceptionFailedToLoadProperties {
            get {
                return ResourceManager.GetString("ExceptionFailedToLoadProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A resource key is required to access the 51Degrees cloud service. Please use the &apos;SetResourceKey&apos; method to supply your resource key. You can obtain one for free from https://configure.51degrees.com.
        /// </summary>
        internal static string ExceptionResourceKeyNeeded {
            get {
                return ResourceManager.GetString("ExceptionResourceKeyNeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to send request. A TaskCanceledException was thrown. The likely cause of this would be a connection timeout..
        /// </summary>
        internal static string ExceptionTaskCanceledRequest {
            get {
                return ResourceManager.GetString("ExceptionTaskCanceledRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cloud service at &apos;{0}&apos; returned status code &apos;{1}&apos; with content {2}..
        /// </summary>
        internal static string MessageErrorCodeReturned {
            get {
                return ResourceManager.GetString("MessageErrorCodeReturned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data in response from cloud service at &apos;{0}&apos;.
        /// </summary>
        internal static string MessageNoDataInResponse {
            get {
                return ResourceManager.GetString("MessageNoDataInResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This method should be overridden in the class derived from CloudAspectEngineBase class. The implementation should use the &apos;json&apos; parameter to populate the &apos;aspectData&apos; accordingly. This method will be called by the CloudAspectEngine.ProcessEngine() method after it has successfully retrieved the JsonResponse from the CloudRequestEngine..
        /// </summary>
        internal static string ProcessCloudEngineNotImplemented {
            get {
                return ResourceManager.GetString("ProcessCloudEngineNotImplemented", resourceCulture);
            }
        }
    }
}
