/* *********************************************************************
 * This Original Work is copyright of 51 Degrees Mobile Experts Limited.
 * Copyright 2025 51 Degrees Mobile Experts Limited, Davidson House,
 * Forbury Square, Reading, Berkshire, United Kingdom RG1 3EU.
 *
 * This Original Work is licensed under the European Union Public Licence
 * (EUPL) v.1.2 and is subject to its terms as set out below.
 *
 * If a copy of the EUPL was not distributed with this file, You can obtain
 * one at https://opensource.org/licenses/EUPL-1.2.
 *
 * The 'Compatible Licences' set out in the Appendix to the EUPL (as may be
 * amended by the European Commission) shall be deemed incompatible for
 * the purposes of the Work and the provisions of the compatibility
 * clause in Article 5 of the EUPL shall not apply.
 *
 * If using the Work as, or as part of, a network application, by
 * including the attribution notice(s) required under Article 5 of the EUPL
 * in the end user terms of the application under an appropriate heading,
 * such notice(s) shall fulfill the requirements of that article.
 * ********************************************************************* */

using FiftyOne.Pipeline.Core.Data;
using FiftyOne.Pipeline.Engines.FlowElements;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace FiftyOne.Pipeline.Engines.Data
{
    /// <summary>
    /// Represents an ElementData instance that is generated by an 
    /// <see cref="IAspectEngine"/>.
    /// This data object will contain property values that relate to 
    /// a specific aspect.
    /// See the <see href="https://github.com/51Degrees/specifications/blob/main/pipeline-specification/conceptual-overview.md#aspect-data">Specification</see>
    /// </summary>
    public interface IAspectData : IElementData
    {
        /// <summary>
        /// The engine that generated the data withing this data instance.
        /// </summary>
        IReadOnlyList<IAspectEngine> Engines { get; }

        /// <summary>
        /// If the engine is configured for lazy loading, this property 
        /// returns a task that will complete once the engine has finished
        /// processing.
        /// Otherwise, it will be null.
        /// </summary>
        Task ProcessTask { get; }

        /// <summary>
        /// Get whether this instance of element data was the result of a 
        /// cache hit, rather than processing of the underlying aspect engine.
        /// This field is only set if the Aspect Engine is configured to do so.
        /// </summary>
        bool CacheHit { get; }
    }
}
