//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FiftyOne.Pipeline.Core {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FiftyOne.Pipeline.Core.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find property &apos;{0}&apos;..
        /// </summary>
        internal static string ExceptionCannotFindProperty {
            get {
                return ResourceManager.GetString("ExceptionCannotFindProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FlowData has already been processed.
        /// </summary>
        internal static string ExceptionFlowDataAlreadyProcessed {
            get {
                return ResourceManager.GetString("ExceptionFlowDataAlreadyProcessed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This instance has not yet been processed.
        /// </summary>
        internal static string ExceptionFlowDataNotYetProcessed {
            get {
                return ResourceManager.GetString("ExceptionFlowDataNotYetProcessed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key name cannot be null.
        /// </summary>
        internal static string ExceptionKeyNameNull {
            get {
                return ResourceManager.GetString("ExceptionKeyNameNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple matches for property &apos;{0}&apos;. Flow elements that populate this property are: {1}.
        /// </summary>
        internal static string ExceptionMultipleProperties {
            get {
                return ResourceManager.GetString("ExceptionMultipleProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ParallelElements instances do not have an element data key.
        /// </summary>
        internal static string ExceptionParallelElementsNoDataKey {
            get {
                return ResourceManager.GetString("ExceptionParallelElementsNoDataKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem with pipeline configuration, failed to create pipeline.
        /// </summary>
        internal static string MessagePipelineCreationFailed {
            get {
                return ResourceManager.GetString("MessagePipelineCreationFailed", resourceCulture);
            }
        }
    }
}
