//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FiftyOne.Pipeline.Engines {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FiftyOne.Pipeline.Engines.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error during check for data update.
        /// </summary>
        internal static string ExceptionAutoUpdate {
            get {
                return ResourceManager.GetString("ExceptionAutoUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update on startup failed for {0} with status {1}. See log for details.
        /// </summary>
        internal static string ExceptionAutoUpdateOnStartupFailed {
            get {
                return ResourceManager.GetString("ExceptionAutoUpdateOnStartupFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred when applying a data update to engine &apos;{0}&apos;.
        /// </summary>
        internal static string ExceptionAutoUpdateRefreshEngine {
            get {
                return ResourceManager.GetString("ExceptionAutoUpdateRefreshEngine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some enabled features ({0}) require an IDataUpdateService but one has not been supplied. This can be corrected by passing an IDataUpdateService instance to the engine builder constructor. If building from configuration, an IServiceProvider instance, able to resolve an IDataUpdateService, must be passed to the pipeline builder..
        /// </summary>
        internal static string ExceptionMissingDataUpdateService {
            get {
                return ResourceManager.GetString("ExceptionMissingDataUpdateService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some enabled features ({0}) require a license key but one has not been supplied. This can be corrected by passing a license key to the engine builder. If building from configuration, check the associated builder implementation to determine the correct parameter name to use..
        /// </summary>
        internal static string ExceptionMissingLicenseKey {
            get {
                return ResourceManager.GetString("ExceptionMissingLicenseKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polling interval timespan too large. Must be less than {0} seconds but is {1} seconds.
        /// </summary>
        internal static string ExceptionPollingIntervalTooLarge {
            get {
                return ResourceManager.GetString("ExceptionPollingIntervalTooLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to retrieve {0} because processing threw an exception in engine(s) &apos;{1}&apos;..
        /// </summary>
        internal static string ExceptionProcessingError {
            get {
                return ResourceManager.GetString("ExceptionProcessingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to retrieve {0} because processing threw multiple exceptions in engine(s) &apos;{1}&apos;..
        /// </summary>
        internal static string ExceptionProcessingMultipleErrors {
            get {
                return ResourceManager.GetString("ExceptionProcessingMultipleErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to retrieve {0} because the processing for engine(s) &apos;{1}&apos; took longer than the specified timeout..
        /// </summary>
        internal static string ExceptionProcessingTimeout {
            get {
                return ResourceManager.GetString("ExceptionProcessingTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update randomization timespan too large. Must be less than {0} seconds but is {1} seconds.
        /// </summary>
        internal static string ExceptionRandomizationTooLarge {
            get {
                return ResourceManager.GetString("ExceptionRandomizationTooLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking for update.
        /// </summary>
        internal static string MessageAutoUpdateCheck {
            get {
                return ResourceManager.GetString("MessageAutoUpdateCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking file system.
        /// </summary>
        internal static string MessageAutoUpdateCheckFileSystem {
            get {
                return ResourceManager.GetString("MessageAutoUpdateCheckFileSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating update check timer.
        /// </summary>
        internal static string MessageAutoUpdateCreateTimer {
            get {
                return ResourceManager.GetString("MessageAutoUpdateCreateTimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating file system watcher.
        /// </summary>
        internal static string MessageAutoUpdateCreateWatcher {
            get {
                return ResourceManager.GetString("MessageAutoUpdateCreateWatcher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating on startup.
        /// </summary>
        internal static string MessageAutoUpdateOnStartup {
            get {
                return ResourceManager.GetString("MessageAutoUpdateOnStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempting to refresh engine with new data.
        /// </summary>
        internal static string MessageAutoUpdateRefreshEngine {
            get {
                return ResourceManager.GetString("MessageAutoUpdateRefreshEngine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registering file with auto update service.
        /// </summary>
        internal static string MessageAutoUpdateRegisterDataFile {
            get {
                return ResourceManager.GetString("MessageAutoUpdateRegisterDataFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unhandled error occurred while checking for automatic updates for engine &apos;{0}&apos;.
        /// </summary>
        internal static string MessageAutoUpdateUnhandledError {
            get {
                return ResourceManager.GetString("MessageAutoUpdateUnhandledError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is because your license and/or data file does not include this property. The property is available with the {0} license/data for the {1}.
        /// </summary>
        internal static string MissingPropertyMessageDataUpgradeRequired {
            get {
                return ResourceManager.GetString("MissingPropertyMessageDataUpgradeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property &apos;{0}&apos; not found in data for element &apos;{1}&apos;. .
        /// </summary>
        internal static string MissingPropertyMessagePrefix {
            get {
                return ResourceManager.GetString("MissingPropertyMessagePrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is because your resource key does not include access to any properties under &apos;{0}&apos;. For more details on resource keys, see our explainer: https://51degrees.com/documentation/_info__resourcekeys.html.
        /// </summary>
        internal static string MissingPropertyMessageProductNotInCloudResource {
            get {
                return ResourceManager.GetString("MissingPropertyMessageProductNotInCloudResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is because the property has been excluded when configuring the engine..
        /// </summary>
        internal static string MissingPropertyMessagePropertyExcluded {
            get {
                return ResourceManager.GetString("MissingPropertyMessagePropertyExcluded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is because your resource key does not include access to this property. Properties that are included for this key under &apos;{0}&apos; are {1}. For more details on resource keys, see our explainer: https://51degrees.com/documentation/4.1/_info__resourcekeys.html.
        /// </summary>
        internal static string MissingPropertyMessagePropertyNotInCloudResource {
            get {
                return ResourceManager.GetString("MissingPropertyMessagePropertyNotInCloudResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The reason for this is unknown. Please check that the aspect and property name are correct..
        /// </summary>
        internal static string MissingPropertyMessageUnknown {
            get {
                return ResourceManager.GetString("MissingPropertyMessageUnknown", resourceCulture);
            }
        }
    }
}
