name: Nightly Package Update

on:
  workflow_dispatch:
  schedule:
    # * is a special character in YAML so quote this string
    - cron:  '0 0 * * *'

jobs:
  Nightly_Package_Update:
    uses: 51Degrees/common-ci/.github/workflows/nightly-package-update.yml@main
    with:
      repo-name: ${{ github.event.repository.name }}
      org-name: ${{ github.event.repository.owner.login }}
      common-ci-ref: 9bdc2bcbcabee0153012fe9b7bb6d3b0e9a00d3f
    secrets:
      token: ${{ secrets.ACCESS_TOKEN }}
